### ISSUE TITLE
Extract ASP.NET-related code to a separate project/NuGet package

### ISSUE THREAD

**Issue by JanLenoch** [Kentico/kontent-delivery-sdk-net#117]
### Motivation

`Microsoft.Extensions.Options` carries quite a lot of dependencies. In case, the consumer of our SDK uses the it in a non-ASP.NET project, they might be unnecessary. 

According to @davidfowl, ["Microsoft.Extensions.* is intended for use outside of ASP.NET  Core."](https://twitter.com/davidfowl/status/1031424924060069888)

Let's wait for the result of the [discussion](https://twitter.com/davidfowl/status/1031424924060069888) and also the result of the [StackOverflow thread](https://stackoverflow.com/questions/51894213/simplified-approach-to-ioptionst) before we go any further.

### Suggested approach

- [ ] Extract the following code to a separate project `KenticoCloud.Delivery.AspNet`:
  - [`DeliveryClient(IOptions<DeliveryOptions>...`](https://github.com/Kentico/delivery-sdk-net/blob/master/KenticoCloud.Delivery/DeliveryClient.cs#L144) to get rid of the `Microsoft.Extensions.Options` reference.
  - [ConfigurationManagerProvider](https://github.com/Kentico/delivery-sdk-net/blob/master/KenticoCloud.Delivery/Configuration/ConfigurationManagerProvider.cs) to get rid of the `Microsoft.Extensions.Configuration`, `Microsoft.Extensions.Configuration.Binder` references.
- [ ] Eventually, replace `private readonly Dictionary<string, StringValues> _queryParameters` with `private readonly Dictionary<string, string> _queryParameters` to get rid of the `Microsoft.Extensions.Primitives` reference.

**Comment by petrsvihlik** [comment]
nobody complained about it ever -> closing
