### ISSUE TITLE
Compare string-based and structured rich text rendering in docu

### ISSUE THREAD

**Issue by JanLenoch** [Kentico/kontent-delivery-sdk-net#122]
### Motivation

While we have good wiki pages on both [string-based](https://github.com/Kentico/delivery-sdk-net/wiki/String-based-rendering-of-modular-content-items-in-Rich-text) and [structured](https://github.com/Kentico/delivery-sdk-net/wiki/Structured-Rich-text-rendering) rendering, we miss a quick comparison of the two.

### Proposed solution

Describe in a few words, when it's better to use one or another. Link the new page from the [generators' wiki](https://github.com/Kentico/cloud-generators-net/wiki).

**Comment by petrsvihlik** [comment]
It's described here: https://docs.kontent.ai/tutorials/develop-apps/get-content/dealing-with-structure-in-rich-text#a-how-structured-rich-text-helps-you
and here https://github.com/Kentico/kontent-generators-net
