### ISSUE TITLE
Asset does not have Height or Width values

### ISSUE THREAD

**Issue by mwebb-bzs** [Kentico/kontent-delivery-sdk-net#171]
The API shows `height` and `width` properties in any linked assets coming back in the JSON, but the `Asset` class provided by `KenticoCloud.Delivery` does not have `Height` or `Width` properties.

We are also using the model generator which regenerates the models when we execute it, so would override our implementation of any `CustomAsset` implementation in our generated models.

**Comment by petrsvihlik** [comment]
good point!
