### ISSUE TITLE
Cannot install Kentico.Kontent.Delivery 12.3.0 to ASP.NET 4.6.1 website

### ISSUE THREAD

**Issue by atifshaikh** [Kentico/kontent-delivery-sdk-net#185]
I tried to add the **Kentico.Kontent.Delivery v12.3.0** nuget package to my ASP.NET website (v4.6.1), but I get the following error every time.  _Kentico Support_ suggested I create an issue here.

> Could not install package 'Kentico.Kontent.Delivery 12.3.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by petrsvihlik** [comment]
hi @atifshaikh!

`Kentico.Kontent.Delivery 12.3.0` targets [`netstandard2.0`](https://github.com/Kentico/kontent-delivery-sdk-net/blob/master/Kentico.Kontent.Delivery/Kentico.Kontent.Delivery.csproj#L4) which means it [should be compatible with .NET Framework 4.6.1](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).

I just tried it and it works fine: https://github.com/petrsvihlik/aspnet_fullfw (see the HomeController)

1) Could you perhaps share exact repro steps or better a repro project where we can narrow down the issue?
2) Does the issue still occur if you upgrade to .NET Framework 4.7.2?

**Comment by BHC-Rob** [comment]
We get the same exact error.  We uninstalled  KenticoCloud.Delivery and via nuget tried to install Kentico.Kontent.Delivery.  12.3 stable.  Any guidance would be appreciated.

**Comment by tomasjurasek** [comment]
@BHC-Rob Which VS you are using?

I think you also need to install [.NET Core SDK](https://dotnet.microsoft.com/download) on your PC for using .NET Standard with .NET Framework 4.6.1 in a project.

**Comment by BHC-Rob** [comment]
Ok, I just wanted to give an update of my progress.  I was using VS 2015 but I decided to open it with VS2017 and uninstall the old Kentico.Delivery sdk via nuget.   The reason I used VS2017 is I wanted to easily clear all Nuget Caches by opening ManageNuget in my project -> Cliciking on Options -> Select General -> Clear All Nuget Cache(s) button. 

 I then installed Kentico.Kontent.Delivery and it installed fine.  I then replaced all Kentico syntax code needed for the updated version (Example:  using Kentico.Deliver is now using Kentico.Kontent.Delivery and the IDelivery client code....

The result was it worked great on my local.  Unfortunately I the tried to publish it to my dev server and it gives this error even after a clean and rebuild.
_Could not load file or assembly 'System.ValueTuple, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)_ 

Still working on this but If anyone has any guidance let me know.
thnx!

**Comment by tomasjurasek** [comment]
@BHC-Rob  You also need .NET Core SDK on your dev/production machine

**Comment by petrsvihlik** [comment]
@BHC-Rob  @atifshaikh may I ask you which version you are upgrading from? There might be several solutions to your problem.

1) As stated before by @tomasjurasek, the best solution is to upgrade your environments in order for them to be able to understand and consume `netstandard2.0` libraries (which is an industry standard at the moment).

2) Our SDK is following Microsoft's [best practices](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) and targets `netstandard2.0`. However, as a temporary solution before you upgrade your ecosystem (see 1), you can craft a custom Delivery SDK package yourselves. Just change `<TargetFramework>netstandard2.0</TargetFramework>` to `<TargetFrameworks>netstandard2.0;net461</TargetFrameworks>` in your csproj (and add `retryAfter = default;` to line 33 in the `HttpResponseHeadersExtensions`, build and run `dotnet pack` to create own NuGet package.

3) If you are trying to address the problem of [changed URLs of API endpoints](https://docs.kontent.ai/reference/api-changelog#a-api-urls-changed), then depending on the version of the SDK you are using, you might be able to take advantage of the `WithCustomEndpoint()` method or set the `ProductionEndpoint` or `PreviewEndpoint` properties via `DeliveryOptions` object or appsettings.json directly to `"https://deliver.kontent.ai/{0}"` and `"https://preview-deliver.kontent.ai/{0}"` respectively. E.g.
```json
"DeliveryOptions": {
  "ProjectId": "975bf280-fd91-488c-994c-2f04416e5ee3",
  "ProductionEndpoint": "https://deliver.kontent.ai/{0}",
  "PreviewEndpoint": "https://preview-deliver.kontent.ai/{0}"
  },
```

**Comment by BHC-Rob** [comment]
@petrsvihlik Sure, currently the site I am initially trying to upgrade the Kentico Delivery is running .net 4.6.1.  After trying to install system.tuple it still did not work.  We are now going to upgrade to .Net 4.7 to see what happens.  This site works fine on my local but on our dev Windows Server 2012 r2 it gives me that unfortunate (System.ValueTuple, Version=0.0.0.0) error.  We want to get this small site working fine before we tackle our bigger sites with confidence.   Thanks for the all the suggestions and we will update as we go along.  👍

**Comment by petrsvihlik** [comment]
@BHC-Rob thank you for the info. What's the version of the Delivery SDK you are upgrading from?

**Comment by BHC-Rob** [comment]
**Update:**  We have installed .NET 4.8 on our dev server and updated our .NET Framework version from 4.6.1 to 4.8 within the website project. Rebuilt and restarted the website that was having the System.Value... issue and it works fine.  So Option 1 to update the .NET environment has worked.  We are going to publish to live when our IT team takes a server snapshot of the live server as a backup.  Thanks everyone for all the suggestions and keep up the good work at Kentico.

**Comment by petrsvihlik** [comment]
Good to hear that you were able to resolve it @BHC-Rob !
