### ISSUE TITLE
Version 13.0.0 Nuget?

### ISSUE THREAD

**Issue by xantari** [Kentico/kontent-delivery-sdk-net#189]
### Brief bug description

It appears 13.0.0 is latest non-beta version, but only 12.3.0 is published to nuget.

Was 13.0.0 pulled?

**Comment by petrsvihlik** [comment]
@xantari yes, it was released by mistake. it was the same as 12.3.0 which is the recommended stable version.
we're working on a brand new version which will contain some new cool features
