### ISSUE TITLE
Create documentation on how to get multiple different clients to register

### ISSUE THREAD

**Issue by xantari** [Kentico/kontent-delivery-sdk-net#190]
### Motivation

We currently are trying to build a website that has content split across two different projects in Kentico Kontent. 

Our requirements are to be able to register separate IDeliveryClient registrations.

We have attempted to solve this using the attached code in the Clients folder.

There are two files. One called ICachingAppsOrgDeliveryClient.cs and the other is ICachingArrtOrgDeliveryClient.cs

In our startup.cs we register those two clients but we can not figure out how to have the DeliveryClientBuilder to return anything other then an IDeliveryClient. Which causes our cast to fail.

You can see this if you search for the comment "//ISSUE HERE" in startup.cs.

Once we can figure out how to register these two different delivery clients we can then use the two different clients in a single controller:

    public class DualKenticoController : Controller
    {
        public DualKenticoController(ICachingArrtOrgDeliveryClient kenticoDeliveryClient1, ICachingAppsOrgDeliveryClient kenticoDeliveryClient2, ILogger<ContentPageController> logger)
        {
            //Code here
        }
    }

Sadly I can't figure out how to register this properly. 

[Kentico Multiple Different Client Issue.zip](https://github.com/Kentico/kontent-delivery-sdk-net/files/4251366/Kentico.Multiple.Different.Client.Issue.zip)

### Proposed solution

Documentation on registering multiple different delivery clients in a single .NET Core project.

**Comment by petrsvihlik** [comment]
Hey @xantari , great question.

You have several options:

1. Create a factory class that would create instances of the DeliveryClient based on a name and inject the factory into the controllers. 


```
public interface IDeliveryClientFactory    { IDeliveryClient Get(string name); }

// + an appropriate implementation of IDeliveryClientFactory

public class DualKenticoController : Controller
{
    public DualKenticoController(IDeliveryClientFactory factory)
    {
      // factory.Get("xyz")....
      // factory.Get("abc")....
    }
}

```
2. Use the [beta version](https://www.nuget.org/packages/Kentico.Kontent.Delivery/13.0.1-beta6) of the SDK that saves you from writing the factory as it already [contains it](https://github.com/Kentico/kontent-delivery-sdk-net/search?q=deliveryclientfactory&unscoped_q=deliveryclientfactory). (Things may change in the beta though...be prepared for that).
3. Use a DI container that supports named/keyed services (e.g. autofac). [Autofac docs](https://autofaccn.readthedocs.io/en/latest/advanced/keyed-services.html), [autofac example](https://stackoverflow.com/a/23992803/1332034)

`3` is a generally accepted practice. Once we have `2` finished, it'll be the best practice for the scenario.

Let me know if you have more questions.

**Comment by xantari** [comment]
Cool, okay the beta version and/or the factory pattern will probably be our way forward. Thanks.

**Comment by xantari** [comment]
@petrsvihlik Can you show me example code on how to get two "AddWebhookInvalidatedCachingClient" services registered with this method?

Can't seem to figure it out...

**Comment by xantari** [comment]
@petrsvihlik  Does this look correct? If so would be helpful to get this added to the boiler plate example and perhaps dancing goat sample.

```
services.AddSingleton<IContentLinkUrlResolver, CustomContentLinkUrlResolver>();
services.AddSingleton<ITypeProvider, CustomTypeProvider>();
services.TryAddSingleton<ICacheManager, CacheManager>();

var deliveryOptions = new DeliveryOptions();
Configuration.GetSection(nameof(DeliveryOptions)).Bind(deliveryOptions);

var deliveryOptionsArrt = new DeliveryOptions();
Configuration.GetSection("DeliveryOptionsArrt").Bind(deliveryOptionsArrt);

services.AddWebhookInvalidatedCachingClientToFactory("Client1", builder =>
{
	return DeliveryClientBuilder
	   .WithOptions(_ => deliveryOptions)
	   .WithTypeProvider(builder.GetService<ITypeProvider>())
	   .WithContentLinkUrlResolver(builder.GetService<IContentLinkUrlResolver>())
	   .Build();
}, (options) =>
{
	//if (Environment.IsDevelopment())
	//{
	//    options.StaleContentTimeout = TimeSpan.FromSeconds(1);
	//    options.DefaultTimeout = TimeSpan.FromHours(1);
	//}
	//else 
	//{
	options.StaleContentTimeout = TimeSpan.FromSeconds(2);
	options.DefaultTimeout = TimeSpan.FromHours(24);
	//}
});
services.AddWebhookInvalidatedCachingClientToFactory("Client2", builder =>
{
	return DeliveryClientBuilder
	   .WithOptions(_ => deliveryOptionsArrt)
	   .WithTypeProvider(builder.GetService<ITypeProvider>())
	   .WithContentLinkUrlResolver(builder.GetService<IContentLinkUrlResolver>())
	   .Build();
}, (options) =>
{
	//if (Environment.IsDevelopment())
	//{
	//    options.StaleContentTimeout = TimeSpan.FromSeconds(1);
	//    options.DefaultTimeout = TimeSpan.FromHours(1);
	//}
	//else 
	//{
	options.StaleContentTimeout = TimeSpan.FromSeconds(2);
	options.DefaultTimeout = TimeSpan.FromHours(24);
	//}
});
```

ServiceCollectionExtensions.cs

```
public static IServiceCollection AddWebhookInvalidatedCachingClientToFactory(this IServiceCollection services, string name, 
	Func<IServiceProvider, IDeliveryClient> baseClientFactory,
	Action<CacheOptions> configureCacheOptions = null)
{
	if (configureCacheOptions != null)
	{
		services.Configure(configureCacheOptions);
	}

	services.TryAddSingleton<ICacheManager, CacheManager>();

	services.AddTransient<IConfigureOptions<DeliveryClientFactoryOptions>>(sp =>
	{
		return new ConfigureNamedOptions<DeliveryClientFactoryOptions>(name, options =>
		{
			options.DeliveryClientsActions.Add(() =>
			{
				return new CachingDeliveryClient(
					 sp.GetRequiredService<ICacheManager>(),
					 baseClientFactory(sp));
			});
		});

	});

	return services;
}
```

**Comment by xantari** [comment]
Hmm... That didn't work. Doesn't seem like it gets registered...

**Comment by xantari** [comment]
@petrsvihlik I had to create my own factory class. Couldn't get the new one in the Beta 6 package setup to use multiple WebhookInvalidatedCachingClient classes...

**Comment by petrsvihlik** [comment]
@tomasjurasek may I ask you to help out @xantari ? (we've made some improvements in the beta SDK which may make the registration easier, but I'll let Tomas answer)

**Comment by tomasjurasek** [comment]
@xantari I'm preparing demo application wit features like DeliveryFactory, Cache, and Registration of multiple clients.

**Comment by xantari** [comment]
@tomasjurasek OK thanks, I am trying to register multiple "WebhookInvalidatedCacheClients" that are in your boilerplate sample...

**Comment by tomasjurasek** [comment]
@xantari  We support these scenarios like DeliveryClientFactory, Multiple configurations of client, Memory cache in **beta** SDK. Look at demo app - https://github.com/tomasjurasek/kontent-delivery-demo

**Comment by xantari** [comment]
@tomasjurasek How do you register your custom ITypeProvider and IContentLinkUrlResolver using this new method?

Also, how do you attach your own HttpClient to each client?

How do you associate a DynamicRouteValueTransformer class to each registered client?

**Comment by xantari** [comment]
I'm using Beta6 and get this:

![image](https://user-images.githubusercontent.com/6610039/76545529-eb401800-6457-11ea-9114-f63c5442aad3.png)

**Comment by tomasjurasek** [comment]
@xantari  now, we have  Beta9. Please look at the demo application, there is referenced.

Of course, you can register specific implementation for each client, for this scenario you can register named client with DeliveryClientBuilder and pass the implementation there.

Or if you want to register custom implementation for all clients, you can use ServiceCollection registration like `services.AddSingleton<ITypeProvider, CustomTypeProvider>()`

**Comment by petrsvihlik** [comment]
Internal reference: https://kentico.atlassian.net/browse/CTC-871

**Comment by petrsvihlik** [comment]
we'll update the wiki https://github.com/Kentico/kontent-delivery-sdk-net/wiki
and especially this page: https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Instantiating-DeliveryClient-with-Configuration-API-and-DI-in-ASP.NET-Core-MVC-apps

with all the new configuration options

**Comment by petrsvihlik** [comment]
updated docs: https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Registering-the-DeliveryClient-to-the-IServiceCollection-in-ASP.NET-Core#registering-multiple-clients

RTM to be released on Thursday
