### ISSUE TITLE
CacheManager is missing a clearing function

### ISSUE THREAD

**Issue by xantari** [Kentico/kontent-delivery-sdk-net#198]
### Motivation

When using the CacheManager (Webhook Caching manager or default cachemanager) it uses IMemoryCache.

However, when implementing a "preview" controller that uses the DeliveryClient it will continue to fetch the cached content. In the case of previewing something that is already cached we need to be able to evict the previously viewed page from cache so we can preview the new "draft" content.

### Proposed solution

Allow for a simple "ClearAll()" method on memory cache.

### Additional context

NA

**Comment by petrsvihlik** [comment]
there's new support for this in the `IDeliveryCacheManager` interface 
https://github.com/Kentico/kontent-delivery-sdk-net/blob/master/Kentico.Kontent.Delivery.Abstractions/IDeliveryCacheManager.cs#L43

which is implemented for `IMemoryCache` in 
https://github.com/Kentico/kontent-delivery-sdk-net/blob/master/Kentico.Kontent.Delivery.Caching/DeliveryCacheManager.cs

this will be a part of the v13 release
