### ISSUE TITLE
Handle publishing of linked items in caching

### ISSUE THREAD

**Issue by JanLenoch** [Kentico/kontent-delivery-sdk-net#199]
### Motivation

When an unpublished content item is put into a Linked items element or a Rich text element, the CachedDeliveryClient has no means of creating a dummy cache entry of that linked item. Hence no invalidation of the parent content item happens when the linked item gets published afterwards.

### Proposed solution

Find a clean way of employing the Preview API to make the caching aware of unpublished linked items.

**Comment by petrsvihlik** [comment]
I believe the publishing mechanism for linked items has changed since. This hasn't been reported as an issue, so I'm closing this one for the time being.
