### ISSUE TITLE
Dimensions on IInlineImage

### ISSUE THREAD

**Issue by robertgregorywest** [Kentico/kontent-delivery-sdk-net#204]
### Motivation

When producing AMP versions of pages, the [amp-img](https://amp.dev/documentation/components/amp-img/) tag requires an explicit size. There may be other scenarios where the size of the image would be useful, such as in generating responsive images. Currently the `IInlineImage` interface does not expose these values so it is not possible to use the standard Kontent image functionality in rich text content, a custom content type must be used.

### Proposed solution

Add width and height to `IInlineImage` and update the `RichTextContentConverter` so that the values for width and height are utilised from the `elementData`. Even if you do not output these values in the `InlineImage` it would be useful to have them available so that the output can be customised to use them.

**Comment by petrsvihlik** [comment]
@robertgregorywest 
thanks for submitting the idea. can you please quickly verify that #205 meets your expectations?

**Comment by robertgregorywest** [comment]
@petrsvihlik 
Yes, I can confirm that #205 exactly meets expectations. You have saved me making the PR, many thanks.

**Comment by petrsvihlik** [comment]
next time then :) 
could you please give it a go: https://github.com/Kentico/kontent-delivery-sdk-net/releases/tag/13.0.1-beta10 and confirm that it works as expected? 
thanks!

**Comment by robertgregorywest** [comment]
I've switched to that beta and all working perfectly, thanks!

**Comment by petrsvihlik** [comment]
glad to help ;)

**Comment by petrsvihlik** [comment]
Hey @robertgregorywest , I took the liberty of linking your article from the docs here: https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Structured-Rich-text-rendering#other-resources
Hope you don't mind :)

Also, the SDK is now out of beta, so you can enjoy a stable release [13.0.1](https://www.nuget.org/packages/Kentico.Kontent.Delivery/13.0.1).

**Comment by robertgregorywest** [comment]
Of course I don't mind, thanks for linking :-)
