### ISSUE TITLE
Consider using IOptionsSnapshot

### ISSUE THREAD

**Issue by JanLenoch** [Kentico/kontent-delivery-sdk-net#212]
### Motivation

Given that the DeliveryClientFactory was designed to produce client instances with a scoped lifetime (as opposed to a singleton-like lifetime), the [IOptionsSnapshot](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.1#reload-configuration-data-with-ioptionssnapshot) appears to be a better fit for accessing configuration data.

### Proposed solution

Consider replacing the current IOptionsMonitor accessor with IOptionsSnapshot.

**Comment by petrsvihlik** [comment]
Why do you think the DeliveryClientFactory was designed to produce scoped instances? 
If you use any of the `IServiceCollection` extensions, it'll register a singleton: https://github.com/Kentico/kontent-delivery-sdk-net/blob/5310022568f5b32f91103a73c601eb70767639d0/Kentico.Kontent.Delivery/Extensions/ServiceCollectionExtensions.cs#L208

Moreover, we originally wanted to implement the `IOptionsSnapshot` but it was not possible for a reason that I can't remember but @tomasjurasek might.

**Comment by JanLenoch** [comment]
Just an assumption, based on previous discussions w/ @alesk-kentico about the problems that the underlying HttpClient had when running for longer periods of time.

**Comment by petrsvihlik** [comment]
No, it's actually a good practice to use HttpClient as a singleton but you need to make sure you use HttpClientFactory for the reasons described at:
- https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net-core
- https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/


We addressed the issues [described here](https://github.com/Kentico/kontent-delivery-sdk-net/issues/182#issuecomment-570083093) and we currently recommend using HttpClientFactory together with the Delivery SDK as the best practice: https://github.com/Kentico/kontent-delivery-sdk-net/wiki
