### ISSUE TITLE
Question on expiration values

### ISSUE THREAD

**Issue by xantari** [Kentico/kontent-delivery-sdk-net#214]
### Motivation

I looked around (albeit briefly) to try find the difference between these two values (StaleContentExpiration and DefaultExpiration)

        services.AddDeliveryClientCache(new DeliveryCacheOptions()
            {
                StaleContentExpiration = TimeSpan.FromSeconds(2),
                DefaultExpiration = TimeSpan.FromMinutes(24)
            });

Could you explain the difference between the two and how they interact with each other?

Maybe put in documentation somewhere (or point me to where it is defined).

### Proposed solution

Just looking for clarification in documentation somewhere.

**Comment by petrsvihlik** [comment]
hi @xantari .

`StaleContentExpiration` relates to my explanation of stale content [here](https://github.com/Kentico/kontent-boilerplate-net/issues/94#issuecomment-602688995). basically, it only makes sense to cache stale content for a few seconds
`DefaultExpiration` is used for the rest

I made a note in #202, we'll address it somewhere in the docs and let you know.

**Comment by petrsvihlik** [comment]
I'm closing the issue now. If you have any additional questions, please feel free to reopen it.

**Comment by petrsvihlik** [comment]
added to the docs here: https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Caching-responses
