### ISSUE TITLE
Memory leak in .NET Core 3.1

### ISSUE THREAD

**Issue by stephenpmmt** [Kentico/kontent-delivery-sdk-net#223]
### Brief bug description

When running a .NET Core application using the Kontent SDK continuously at low load (single request at a time, a few hundred requests in total) significant amounts of memory are used up. This causes requests to take significant amounts of time to be processed, rendering the application unusable. Note there is no real load on the application – just one request at a time, numbering 100-200 requests.

### Repro steps

1. Create a .NET Core application
2. Add the Kontent Delivery SDK nuget package
3. Register the SDK using IServiceCollection.AddDeliveryClient(string, IConfiguration, string)
4. Inject IDeliveryClientFactory into the application and resolve an IDeliveryClient instance using IDeliveryClientFactory.Get(string)
5. Hit a page that causes IDeliveryClientFactory.Get(string) to be hit. Repeatedly hit this page
6. Use the Visual Studio Diagnostic tools to take a memory snapshot. Order by count (high to low) - you will see large numbers of objects related to cancellationtokens, IOptions and Kentico.Kontent.Delivery.DeliveryOptions

### Expected behavior

No build up of objects in memory.

### Test environment

 - Windows 10 running in IIS express for debugging but other environments also, including linux
 - Kontent Delivery SDK version is 13.0.1
 - Runtime version is .NET Core 3.1

### Additional context

The Visual Studio Profiler shows memory usage as in this image:
![Kontent SDK Memory Leak](https://user-images.githubusercontent.com/69504408/89875245-f046f600-dbb4-11ea-82ce-da4c4a0db343.JPG)
Note in particular the million+ instances of OptionsMonitor<Kentico.Kontent.Delivery.DeliveryOptions> highlighted in the top half of the image. “Paths to Root” appears to indicate that other high count objects (with a million+ instances) are related to these options instances (something backed up by the very similar counts).
 
In my investigation I then removed all calls to the Kontent SDK, mocking out responses from the SDK, to observe any difference – the result was that memory leaks were completely removed and performance was at expected levels, including under high load. The key call that seems to cause the issue is IDeliveryClientFactory.Get(string) – the inclusion of this call causes the memory leak, and subsequent performance issues.
 
Additional note: we are aware that responses from the Kontent API should be cached, and we do have this facility in place. However, the memory used is not something that gets collected quickly (if ever), so even modest/low numbers of calls to the API will cause severe performance issues and these will degrade quickly, with the behaviour we are seeing.

### Screenshots

Attached

**Comment by petrsvihlik** [comment]
Hi @stephenpmmt ,
thank you for reporting the issue and for very clear steps to reproduce!

We kicked off an investigation and will be testing several different fixes this week (caching the factory results, etc.) We should have more info about the final approach by the end of the week. We'll keep you posted.

In the meantime, it'd be great if you could help us out too. You can clone the project, debug it, and suggest improvements.

**Comment by petrsvihlik** [comment]
We applied a fix which we believe should help.

**Before:**
![before](https://user-images.githubusercontent.com/9810625/89941678-a6ddc180-dc1b-11ea-9189-0921b361f612.png)

**After:**
![after](https://user-images.githubusercontent.com/9810625/89941674-a5ac9480-dc1b-11ea-8b69-01c02bb2725e.png)

Can you please try out this release? https://github.com/Kentico/kontent-delivery-sdk-net/releases/tag/13.0.2

**Comment by stephenpmmt** [comment]
Thank you @petrsvihlik. I've done some preliminary testing on 13.0.2 and I see no significant memory usage at all now, and this includes scenarios under heavy load.

I will continue to test but so far this looks like a significant improvement.

**Comment by petrsvihlik** [comment]
thank you!
