### ISSUE TITLE
GetItemsAsync<T> doesn't restrict to the content type defined by T

### ISSUE THREAD

**Issue by xantari** [Kentico/kontent-delivery-sdk-net#227]
### Brief bug description

Testing 14.0.0-rc1 and found the following line of code in our project isn't working correctly:

```
var client = _clientFactory.Get(Constants.ArrtOrgClientKey);
var redirectList = await client.GetItemsAsync<UrlRedirectList>(new DepthParameter(5));
```

This should return only one record in our environment, but it's returning thousands of items (doesn't seem to be restricted based off of the UrlRedirectList content type code name)?

This however does work:

```
var redirectList = await client.GetItemsAsync<UrlRedirectList>(new List<IQueryParameter>
{
      new DepthParameter(5),
      new InFilter("system.type", UrlRedirectList.Codename)
});
```

Should it obey the old behavior, or should we always require InFilter("system.type") parameter in all GetItemsAsync requests?

### Repro steps

Use GetItemsAsync&lt;T&gt; and you'll find it doesn't seem to be restricting properly.

### Expected behavior

Should return only the content types defined by T (in the above example this would be UlrRedirectList, code name == url_redirect_list in our environment)

### Test environment

- Version 14.0.0.-rc1

**Comment by tomasjurasek** [comment]
Hi @xantari,

I'm trying to reproduce on our DancingGoat sample project and there is works fine.

Can you please try to generate the models by our beta generator [link](https://github.com/Kentico/kontent-generators-net/releases/tag/6.0.0-beta4)?

T

**Comment by xantari** [comment]
I did re-generate (no changes in my models occurred though coming from 14.0.0-beta 6:

![image](https://user-images.githubusercontent.com/6610039/90421096-7f08b680-e07e-11ea-9900-9d521240741d.png)

This is what I'm seeing:

![image](https://user-images.githubusercontent.com/6610039/90421000-5e406100-e07e-11ea-8a50-cd2dddffbf8b.png)

This is what I should see:

![image](https://user-images.githubusercontent.com/6610039/90421181-a069a280-e07e-11ea-8ce2-24d582c1db8a.png)

**Comment by tomasjurasek** [comment]
@xantari Do you have registered an ITypeProvider?

**Comment by xantari** [comment]
Yes, can you QC my config. It is as follows:

```
public static void AddKentico(this IServiceCollection services, IWebHostEnvironment environment, IConfiguration configuration, ProjectOptions projectOptions)
        {
            services.Configure<DeliveryCacheOptions>((options) =>
            {
                //The preview and dev environments turn off caching so that the preview button works within Kentico Kontent
                if (environment.IsDevelopment() || environment.IsEnvironment(Constants.Preview)
                    || environment.IsEnvironment(Constants.DevPreview) || environment.IsEnvironment(Constants.DevImpersonation)
                    || environment.IsEnvironment("LocalDevelopment")
                    )
                {
                    options.StaleContentExpiration = TimeSpan.FromSeconds(1);
                    options.DefaultExpiration = TimeSpan.FromSeconds(1);
                }
                else //Production caches everything 
                {
                    options.StaleContentExpiration = TimeSpan.FromSeconds(2);
                    options.DefaultExpiration = TimeSpan.FromHours(24);
                }
            });

            services.AddSingleton<IContentLinkUrlResolver, CustomContentLinkUrlResolver>();
            services.AddSingleton<ITypeProvider, CustomTypeProvider>();
            services.AddSingleton<IDeliveryCacheManager, MemoryCacheManager>();

            var deliveryOptions = new DeliveryOptions();
            configuration.GetSection(Constants.ArrtOrgDeliveryOptionsConfigKey).Bind(deliveryOptions);

            //https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Registering-the-DeliveryClient-to-the-IServiceCollection-in-ASP.NET-Core#registering-multiple-clients
            services.AddDeliveryClient(Constants.ArrtOrgClientKey, (bld) =>
            {
                return bld
                    .BuildWithDeliveryOptions(_ => deliveryOptions)
                    .Build();
            });
        }
    }
```

**Comment by tomasjurasek** [comment]
@xantari I think, there is a problem with registration.

You have registered your CustomTypeProvider in IoC Container, but you are building named IDeliveryClient by builder manually, and when you build your client by builder there is no connection with IoC Container.

I'm recommending you register .AddDeliveryClient automatic like:

`services.AddDeliveryClient(Constants.ArrtOrgClientKey, deliveryOptions);`

**Comment by xantari** [comment]
That was the issue. Closing this. This was also the issue for #228 which I will also close.
