### ISSUE TITLE
Issue with IHostedServices using Memory Cache along with 14.0.0-rc1 custom content link URL Resolvers

### ISSUE THREAD

**Issue by xantari** [Kentico/kontent-delivery-sdk-net#230]
### Brief bug description

I have a IHostedService which starts on app startup before anything else. It's purpose is to get taxonomy data for a custom sitemap based route transformer (seo friendly URLs).

We place the taxonomy data from Kentico into an IMemoryCache.

In 14.0.0-beta6 and prior versions this worked, but in 14.0.0-rc1 it is no longer working. It seems to lose the instance of the memory cache that I was using once Kentico gets to using the IContentLinkUrlResolver area to resolve the richtext content URLs. And thus I can't lookup any of my data I cached during the IHostedService startup. 

UPDATE: The other thing is, this may have always been an issue in prior versions. I have updated the comment below as I was also using my own Delivery Client factory (this was before you added a client factory). I have since switched to your client factory, and I think it's due to how you call the BuildServiceProvider() function (see comment below) when using named instances in your version of the delivery client factory.

Here is my IHostedService:

```
 /// <summary>
    /// This class initializes some Kentico data to figure out the controller mappings and sitemap information very early in the app startup process
    /// https://andrewlock.net/running-async-tasks-on-app-startup-in-asp-net-core-3/
    /// </summary>
    public class SitemapCacheHostedService : IHostedService
    {
        // We need to inject the IServiceProvider so we can create the scoped service, IDeliveryClient
        private readonly IServiceProvider _serviceProvider;
        private readonly IMemoryCache _memoryCache;
        private readonly IDeliveryClientFactory _clientFactory;
        private readonly ILogger<SitemapCacheHostedService> _logger;

        public SitemapCacheHostedService(IServiceProvider serviceProvider, IMemoryCache cacheManager, IDeliveryClientFactory clientFactory, ILogger<SitemapCacheHostedService> logger)
        {
            _serviceProvider = serviceProvider;
            _memoryCache = cacheManager;
            _clientFactory = clientFactory;
            _logger = logger;
        }

        public async Task StartAsync(CancellationToken cancellationToken)
        {
            _logger.LogInformation("Initializing sitemap cache and controller mappings");
            // Create a new scope to retrieve scoped services
            using (var scope = _serviceProvider.CreateScope())
            {
                var deliveryClient = _clientFactory.Get(Constants.ArrtOrgClientKey);

                var taxonomies = await _memoryCache.GetTaxonomy(deliveryClient);

                await _memoryCache.GetControllerMappings(deliveryClient);
            }
            _logger.LogInformation("Initlized sitemap cache and controller mappings");
        }

        // noop
        public Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;
    }
```

Here is my custom content link URL resolver:

```
/// <summary>
    /// Sample implementation to resolve links to other content items in Rich Text
    /// </summary>
    /// <seealso cref="Kentico.Kontent.Delivery.IContentLinkUrlResolver" />
    public class CustomContentLinkUrlResolver : IContentLinkUrlResolver
    {
        private readonly IMemoryCache _memoryCache;
        private readonly ILogger<CustomContentLinkUrlResolver> _logger;
        private readonly ProjectOptions _projectOptions;

        public CustomContentLinkUrlResolver(IMemoryCache memoryCache, ILogger<CustomContentLinkUrlResolver> logger, IOptions<ProjectOptions> projectOptions)
        {
            _memoryCache = memoryCache;
            _logger = logger;
            _projectOptions = projectOptions.Value;
        }

        /// <summary>
        /// Resolves the link URL.
        /// </summary>
        /// <param name="link">The link.</param>
        /// <returns>A relative URL to the page where the content is displayed</returns>
        public async Task<string> ResolveLinkUrl(IContentLink link)
        {
            List<ControllerMapping> mappings = null;
            _memoryCache.TryGetValue(Constants.ControllerMappingCacheKey, out mappings);

            if (!_projectOptions.RootPageCodeNames.Contains(link.ContentTypeCodename))
            {
                _logger.LogError(@"Someone has linked to an unexpected content type on a page or other area. While kentico allows you to link to anything, 
                it is expected that page links be only to root content items such as landing pages, content pages, or news articles and not to things 
                like jumbotron objects or other types of primitive content type structures in Kentico. Link: {@link}", link);
                return "unsupported_linking_item";
            }

            if (mappings != null && mappings.Count() > 0)
            {
                var contentItem = mappings.FirstOrDefault(p => p.PageCodeName == link.Codename);
                return contentItem.FullUrl;
            }
            return await Task.FromResult(string.Empty);
        }

        /// <summary>
        /// Resolves the broken link URL.
        /// </summary>
        /// <returns>A relative URL to the site's 404 page</returns>
        public async Task<string> ResolveBrokenLinkUrl()
        {
            // Resolves URLs to unavailable content items
            return await Task.FromResult("/404");
        }
    }
```

The problem is, that even though I initialized everything properly in my IHostedService and if I interrogate the memory cache the cache count is > 0, once I get to the IContentLinkUrlResolver and fetch what I expected to be there, it is missing. In fact the entire memory cache up to that point is empty.

Thus all custom content links are not able to be resolved properly.

It is this line in the IContentLinkUrlResolver that is no longer finding anything:

```
 _memoryCache.TryGetValue(Constants.ControllerMappingCacheKey, out mappings);
```

What I think is happening is you are re-initializing your own copy of the memoryCache and overwriting the one that gets created during app startup which isn't good...

It could also be your Clear function that is doing it?

FYI, here is my Kentico Startup:

```
public static void AddKentico(this IServiceCollection services, IWebHostEnvironment environment, IConfiguration configuration, ProjectOptions projectOptions)
        {
            var cacheOptions = new DeliveryCacheOptions();
            cacheOptions.CacheType = CacheTypeEnum.Memory;
            //The preview and dev environments turn off caching so that the preview button works within Kentico Kontent
            if (environment.IsDevelopment() || environment.IsEnvironment(Constants.Preview)
                || environment.IsEnvironment(Constants.DevPreview) || environment.IsEnvironment(Constants.DevImpersonation)
                || environment.IsEnvironment("LocalDevelopment"))
            {
                cacheOptions.StaleContentExpiration = TimeSpan.FromSeconds(1);
                cacheOptions.DefaultExpiration = TimeSpan.FromSeconds(1);
            }
            else //Production caches everything 
            {
                cacheOptions.StaleContentExpiration = TimeSpan.FromSeconds(2);
                cacheOptions.DefaultExpiration = TimeSpan.FromHours(24);
            }
            services.Configure<DeliveryCacheOptions>((options) =>
            {
                options = cacheOptions;
            });

            services.AddSingleton<IContentLinkUrlResolver, CustomContentLinkUrlResolver>();
            services.AddSingleton<ITypeProvider, CustomTypeProvider>();

            var deliveryOptions = new DeliveryOptions();
            configuration.GetSection(Constants.ArrtOrgDeliveryOptionsConfigKey).Bind(deliveryOptions);

            //https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Registering-the-DeliveryClient-to-the-IServiceCollection-in-ASP.NET-Core#registering-multiple-clients
            services.AddDeliveryClient(Constants.ArrtOrgClientKey, deliveryOptions);
            services.AddDeliveryClientCache(Constants.ArrtOrgClientKey, cacheOptions);
        }
```

### Expected behavior

IMemoryCache items that are added outside of kentico's usage should remain.

### Test environment

- Version 14.0.0-rc1

**Comment by xantari** [comment]
I have a theory as to whats happening here.

I'm looking at how you add your delivery clients and I think it's these lines:

https://github.com/Kentico/kontent-delivery-sdk-net/blob/3f37ecd82f34a88c70bedea0b5f92617ca14d2e8/Kentico.Kontent.Delivery/Extensions/ServiceCollectionExtensions.cs#L74

```
 var serviceProvider = services.BuildServiceProvider();
```

From my understanding this type of call creates additional copies of singleton services, so the IMemoryCache I have is not necessarily the one that this delivery client is using due to this issue:

https://stackoverflow.com/questions/58999401/calling-buildserviceprovider-from-application-code-results-in-copy-of-singleto

So I think you need to stop doing that, or I need to revert back to my own Delivery Client factory class.

Atleast that is my theory as to whats happening.

**Comment by xantari** [comment]
So I've pretty much confirmed it is that BuildServiceProvider() issue cause I changed from this:

```
       services.AddDeliveryClient(Constants.ArrtOrgClientKey, deliveryOptions);
       services.AddDeliveryClientCache(Constants.ArrtOrgClientKey, cacheOptions);
```

To this:

```
            services.AddDeliveryClient(deliveryOptions);
            services.AddDeliveryClientCache(cacheOptions);
```

And this issue goes away.

I did this cause I noticed you don't call the BuildServiceProvider() function when you are not doing named clients.

**Comment by xantari** [comment]
I got to thinking why you might be calling BuildServiceProvider in the first place and my only thought would be ensure the cache is unique amongst each client. I propose instead of creating seperate instances of IMemoryCache objects, with one assigned to each delivery client, that you merely just append the name of the delivery client as part of the cache key instead since we know each delivery client will have a unique name.

**Comment by petrsvihlik** [comment]
Interesting. Let me take a look at it :)

**Comment by petrsvihlik** [comment]
Are you registering another `IMemoryCache` outside the `AddKentico` method?

If you want to use a single `IMemoryCache` object throughout the whole application, one thing you may try is to register it explicitly (`services.AddSingleton<IMemoryCache>();`) as a singleton before any of the `AddDelivery*` methods. The SDK will then reuse this singleton.

I don't think an instance of `IMemoryCache` can get lost...you might want to verify how many instances are actually registered by injecting `IEnumerable<IMemoryCache> memoryCaches` instead of just a single `IMemoryCache memoryCache`. 

Let us know the results, please, so that we can continue the investigation. (Not sure if you can, but sharing the whole of the project where the `IHostedService` resides would help too.)

**Comment by xantari** [comment]
I'm making a simple repro for you, how do I share it securely with you (has our API keys in it)

**Comment by xantari** [comment]
FYI, I sent you an invite to download it from my google drive. Set a breakpoint at line # 43 in SitemapCacheHostedService.cs to see that the _memoryCache.Count > 0 and also set a breakpoint at line # 29 in CustomContentLinkUrlResolver.cs to see that _memoryCache when entering the customcontentlinkurl resolver that the _memoryCache.count is no longer 1 but is now 0 (because it's a new copy of the IMemoryCache)

**Comment by petrsvihlik** [comment]
Perfect, I'll check it out tomorrow!

**Comment by petrsvihlik** [comment]
This is indeed a very interesting observation but also a very specific use case.
You are right that it's caused by the fact that the `IDeliveryClient` gets resolved from a different `IServiceProvider` than the `IMemoryCache` that's being injected into the `SitemapCacheHostedService`.

One way you can work around it is by replacing the descriptor `services.AddMemoryCache();` with a specific instance `services.AddSingleton<IMemoryCache>(new MemoryCache(new MemoryCacheOptions(/**/)));`.

I'll need to ask @tomasjurasek to do a bit more digging and decide whether it's even possible to fix it (within the current design constraints) or whether the registration of named services shall be rethought completely.

Since this is a really specific scenario, I think the workaround could suffice but I can envision similar problems arising in the future. On the other hand, I can't think of anything specific atm so I wouldn't hurry with rearchitecting the current solution.

**Comment by tomasjurasek** [comment]
@xantari Try to use our new [release candidate - 14.0.0-rc3](https://github.com/Kentico/kontent-delivery-sdk-net/releases/tag/14.0.0-rc3)

**Comment by xantari** [comment]
Thanks! I'll try it out as soon as I can.

**Comment by mcetkovsky** [comment]
How to properly register Kentico starting after this change?

I've deleted `AddDeliveryClient()` so only the following is kept: 

```
services.Configure<DeliveryOptions>(Configuration.GetSection("KenticoKontent:DeliveryOptions"));
```

I'm getting the following error afterwards:

```
InvalidOperationException: Unable to resolve service for type 'Kentico.Kontent.Delivery.Abstractions.IDeliveryClient' while attempting to activate 'Controllers.HomeController'.
```

**Comment by tomasjurasek** [comment]
@mcetkovsky Hi, nothing changes about register Kentico SDK after this change. Please follow the README or Wiki for setup.

**Comment by mcetkovsky** [comment]
I've just found why AddDeliveryClient was not recognized. In the meantime, it moved from Microsoft.Extensions.DependencyInjection to the Kentico.Kontent.Delivery.Extensions namespace in this commit https://github.com/Kentico/kontent-delivery-sdk-net/commit/a0c00943e6ddbd56c09665f82c0d87ea7a94b4ba.
