### ISSUE TITLE
Cache race condition exists in 14.0.0-rc1

### ISSUE THREAD

**Issue by xantari** [Kentico/kontent-delivery-sdk-net#234]
### Brief bug description

We use the preview functionality in Kentico Kontent. That preview functionality looks up up what type of Content Type it is by the passed in code name and ends up redirecting to the appropriate MVC controller for that content type. We don't know the content type ahead of time, so we use GetItemAsync<object> and figure out which MVC controller to route to from that.

The issue however, is there appears to be a race condition where by the first lookup succeeds, but the second lookup fails. 

If you put in a thread.sleep between the two calls it succeeds (which made me title this as a race condition).

Since this requires data to retrieve, i've created a sample that pulls from our real environment. @petrsvihlik should have received the invite email to the code base that repro's this issue.

### Repro steps

Set a break point in the HomeController.cs at line # 23 (The return View(); line)

You will notice that "response" has a value, but "response2" does not, even though it should have picked up the item from the cache for response2.

If you place a thread.sleep(5000) between "var response" and "var response2" both items will have a value and response2 will no longer be null.

```
    public class HomeController : Controller
    {
        private readonly IDeliveryClientFactory _factory;
        public HomeController(IDeliveryClientFactory clientFactory) {
            _factory = clientFactory;
        }
        public async Task<IActionResult> Index()
        {
            var deliveryClient = _factory.Get();
            var response = await deliveryClient.GetItemAsync<object>("home", new DepthParameter(100));
            var response2 = await deliveryClient.GetItemAsync<LandingPage>("home", new DepthParameter(100));
            return View();
        }
    }
}
```

Example code that shows the race condition as "fixed"

```
    public class HomeController : Controller
    {
        private readonly IDeliveryClientFactory _factory;
        public HomeController(IDeliveryClientFactory clientFactory) {
            _factory = clientFactory;
        }
        public async Task<IActionResult> Index()
        {
            var deliveryClient = _factory.Get();
            var response = await deliveryClient.GetItemAsync<object>("home", new DepthParameter(100));
            Thread.Sleep(5000);
            var response2 = await deliveryClient.GetItemAsync<LandingPage>("home", new DepthParameter(100));
            return View();
        }
    }
}
```

### Expected behavior

Both calls should succeed in retrieving the kentico content without having to do a Thread.Sleep

### Test environment

- Version 14.0.0-rc1

**Comment by xantari** [comment]
@tomasjurasek It appears Petr is out of office for a few days. CCing you on this as well.

**Comment by tomasjurasek** [comment]
Hi, my email is jurasek.tomas@gmail.com

**Comment by xantari** [comment]
Added, you should have gotten an invite email.

**Comment by tomasjurasek** [comment]
@xantari thanks. The second code snippet working for you, because you have 1s cache expiration and between Sleep cache expired.

But I found the issue what you mean. MemoryCache serializes the actual data - `object ` and when you want to reserialize you want another data type - the memory cache returns null.

I will investigate this type of problem and we will see what can we do.

**Comment by xantari** [comment]
Gotcha, I don't recall seeing this behavior in the 13.x version (admittedly I didn't test this exact same scenario with the older version).

**Comment by xantari** [comment]
@tomasjurasek Any updates on this one?

**Comment by tomasjurasek** [comment]
@xantari Hi, sorry for the delay. For now, we don't have any update on this workflow - this is not the SDK issue, but how the memory cache serialization works.

**Comment by xantari** [comment]
@tomasjurasek I wonder if the easy fix is to add the requested type info (object versus the more concrete type generated from the model generator) as part of the cache key?

Then if you request this:
```
var response = await deliveryClient.GetItemAsync<object>("home", new DepthParameter(100));
```
It gets _object_ as part of the cache key.

Versus this:
```
var response2 = await deliveryClient.GetItemAsync<LandingPage>("home", new DepthParameter(100));
```

Would get _landingpage_ as part of it's cache key instead.

Making it so that both lookups succeed.

Matt

**Comment by petrsvihlik** [comment]
@xantari yeah, this looks like an obvious solution...let me check whether it's the best one for now.

**Comment by petrsvihlik** [comment]
well, I think it makes sense to store the responses under different cache keys since they contain different data.

if you'd want to reuse what's already cached and use it in a strongly-typed fashion, you can always do that:

```c#
var response2 = await deliveryClient.GetItemAsync<object>("home", new DepthParameter(100));
LandingPage lp = (LandingPage) response2.Item; 

// and similarly cast the whole collection of `Items` when calling `GetItemsAsync` (plural)
```

let me draft a PR

**Comment by petrsvihlik** [comment]
the fix will be included in the next RC

**Comment by xantari** [comment]
@petrsvihlik Would this still be the recommended webhook eviction logic?

```
        [HttpPost]
        public async Task<IActionResult> Index([FromBody] WebhookModel model)
        {
            if (model != null)
            {
                _logger.LogInformation("Webhook invalidation event: {@data}", model);
                var dependencies = new HashSet<string>();
                if (model.Data.Items?.Any() == true)
                {
                    foreach (var item in model.Data.Items ?? Enumerable.Empty<Item>())
                    {
                        dependencies.Add(CacheHelpers.GetItemDependencyKey(item.Codename));
                    }

                    dependencies.Add(CacheHelpers.GetItemsDependencyKey());
                }

                if (model.Data.Taxonomies?.Any() == true)
                {
                    foreach (var taxonomy in model.Data.Taxonomies ?? Enumerable.Empty<Taxonomy>())
                    {
                        dependencies.Add(CacheHelpers.GetTaxonomyDependencyKey(taxonomy.Codename));
                    }

                    dependencies.Add(CacheHelpers.GetTaxonomiesDependencyKey());
                    dependencies.Add(CacheHelpers.GetItemsDependencyKey());
                    dependencies.Add(CacheHelpers.GetTypesDependencyKey());
                }

                if (model.Message.Type == "content_type")
                {
                    dependencies.Add(CacheHelpers.GetTypesDependencyKey());
                }

                foreach (var dependency in dependencies)
                {
                    await _cacheManager.InvalidateDependencyAsync(dependency);
                }
            }

            return Ok();
        }
```

**Comment by petrsvihlik** [comment]
If you mean whether the same eviction logic is recommended for the `IDistributedCaching` implementation, then no.

Contrary to `IMemoryCache`, `IDistributedCache` does not support [expiration tokens](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.memory.memorycacheentryextensions.addexpirationtoken?view=dotnet-plat-ext-3.1). More on that [here](https://www.devtrends.co.uk/blog/custom-response-caching-in-asp.net-core-with-cache-invalidation) and [here](https://www.devtrends.co.uk/blog/a-guide-to-caching-in-asp.net-core).

> DistributedCacheEntryOptions offers absolute and sliding expiration much like MemoryCacheEntryOptions but token based expiration is absent. This makes adding cache dependencies much more of a challenge and you will need to roll your own implementation if you need this functionality.


So for cache eviction, you can only use like keys generated by `CacheHelpers.GetItemKey()` and `GetItemsKey()` but not `GetItemsDependencyKey()`. (The same logic applies to Types, Elements, and Taxonomies.) You can see which eviction methods are supposed to work fine with the distributed cache if you take a look at the [tests](https://github.com/Kentico/kontent-delivery-sdk-net/blob/master/Kentico.Kontent.Delivery.Caching.Tests/DeliveryClientCacheTests.cs). Search for those marked with `[InlineData(CacheTypeEnum.Distributed)]`.

**Comment by xantari** [comment]
Thanks, so for IMemoryCache the code is still valid though right?

Am I correct in assuming since we can't do dependencies, that even though I evicted something from the distributed cache I may end up getting stale content from a dependency?

**Comment by petrsvihlik** [comment]
Yes to both questions.

- The code is still valid for IMemoryCache...nothing has changed in the implementation really.
- The dependencies with IDistributedCache are tricky. Let's say you have content items A and B. Both are stored in the cache and can be evicted easily. But once B is contained in linked items (formerly modular content) of A then it poses a problem -> you also need to invalidate A when B changes. This is currently solved (in the IMemoryCache implementation) by the expiration tokens (which are in fact cache dependencies). I don't think there is much one can do about it:
  - There is no way of querying cache items (so that one could create some ingenious naming convention for cache keys that would contain the dependencies and that would all be possible to evict in bulk)
  - It's not possible to clear the whole cache (which is, in a way, [possible](https://stackoverflow.com/a/45543023/1332034) with IMemoryCache)
  - We are stuck with [absolute or sliding expiration](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.distributed.distributedcacheentryoptions?view=dotnet-plat-ext-3.1)...

It's not a bug, it's a feature 🙂.
