### ISSUE TITLE
Provide better access to error messages

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/kontent-delivery-sdk-net#251]
### Motivation

Provide better access to error messages, e.g. when an item is [not found](https://deliver.kontent.ai/975bf280-fd91-488c-994c-2f04416e5ee3/items/abcdefg), the user should have access to a strongly-typed error object to be able to differentiate the logic based on error codes.

And use e.g. the `catch-when` pattern: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/when

### Proposed solution

Enrich the [`IApiResponse`](https://github.com/Kentico/kontent-delivery-sdk-net/blob/master/Kentico.Kontent.Delivery.Abstractions/SharedModels/IApiResponse.cs) with an Error object containing the message, request id, error code, and specific code.

### More context
- [related intercom convo](https://app.intercom.com/a/apps/e42kus8l/inbox/inbox/conversation/19590600083373)

**Comment by daddywhite** [comment]
This would be most useful. At the moment the deliveryClient just errors when it doesnt find an item or something else goes wrong.

It would be good if we had instant access to a "Success" boolean and an object containing any relevant error messages.

**Comment by petrsvihlik** [comment]
will be part of the v15 release (in a couple of weeks)
