### ISSUE TITLE
Allow for fixed expiration on memory cache

### ISSUE THREAD

**Issue by pablojmp** [Kentico/kontent-delivery-sdk-net#252]
### Motivation

When using the DeliveryClientCache, one can only set a sliding expiration via DeliveryCacheOptions.DefaultExpiration. If no webhooks are set up for the app and the cache is accessed frequently, there's no way to evict older content.

### Proposed solution
Add a parameter to select what type of expiration DefaultExpiration has (i.e. DefaultExpirationType = Absolute | Sliding) and set the expiration accordingly in [here](https://github.com/Kentico/kontent-delivery-sdk-net/blob/e48cd0031fb400378cf0d764c0ce9cd1ea6f095b/Kentico.Kontent.Delivery.Caching/MemoryCacheManager.cs#L69)

**Comment by tomasjurasek** [comment]
Hi, thanks for the feedback. You right, there is missing support for the expiration type for the memory cache. 

In a few days, I will implement this expiration type enum :)

**Comment by pablojmp** [comment]
@tomasjurasek thanks a lot for the quick response! is it too much to ask for an ETA on the release of the nuget version that'll contain the patch?

**Comment by petrsvihlik** [comment]
baking the build at https://github.com/Kentico/kontent-delivery-sdk-net/releases/tag/14.2.0

**Comment by petrsvihlik** [comment]
@pablojmp here you go: https://www.nuget.org/packages/Kentico.Kontent.Delivery/14.2.0 

please let us know if it works fine for you ;)

**Comment by pablojmp** [comment]
will test right away! thanks guys, that was ultra fast!

**Comment by pablojmp** [comment]
i was testing this configuration
  ```
services.AddDeliveryClientCache(new DeliveryCacheOptions
  {
      StaleContentExpiration = TimeSpan.FromSeconds(2),
      DefaultExpirationType = CacheExpirationType.Absolute,
      DefaultExpiration = TimeSpan.FromSeconds(10),
      CacheType = CacheTypeEnum.Memory
  });
```
while using wireshark to sniff the traffic.
if i keep refreshing a page that fetches content, i don't see more requests to kentico, event after the 10 seconds windows. if i stop refreshing the page and wait 10 seconds before refreshing, the sdk make the request again. it's behaving as a sliding expiration. am i missing something in the configuration?

**Comment by pablojmp** [comment]
Maybe this line https://github.com/Kentico/kontent-delivery-sdk-net/blob/e48cd0031fb400378cf0d764c0ce9cd1ea6f095b/Kentico.Kontent.Delivery.Caching/Extensions/ServiceCollectionExtensions.cs#L56

**Comment by pablojmp** [comment]
@petrsvihlik @tomasjurasek can you reopen this one?

**Comment by pablojmp** [comment]
@tomasjurasek don't worry, i'm the one who feels sorry for throwing more work at you 😄
thanks again!

**Comment by pablojmp** [comment]
confirmed: it's working as intended, thanks!
