### ISSUE TITLE
15.0.0-alpha1 Issues discovered during a testing session

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/kontent-delivery-sdk-net#261]
# Unable to cast object

The method:
`public static IServiceCollection AddDeliveryClient(this IServiceCollection services, string name, IConfiguration configuration, string configurationSectionName = "DeliveryOptions", CustomServiceProviderType customServiceProviderType = CustomServiceProviderType.None)`

is causing the following exception:

> System.InvalidCastException: Unable to cast object of type 'Microsoft.Extensions.Configuration.ConfigurationSection' to type 'Kentico.Kontent.Delivery.Abstractions.DeliveryOptions'.
>    at Kentico.Kontent.Delivery.Extensions.DependencyInjection.Extensions.ServiceCollectionExtensions.AddDeliveryClient(IServiceCollection services, String name, IConfiguration configuration, String configurationSectionName, CustomServiceProviderType customServiceProviderType)

I think it might be caused by the new internal member of the `DeliveryOptions`.

Could you please cover `Kentico.Kontent.Delivery.Extensions.DependencyInjection.Extensions.ServiceCollectionExtensions` with tests?

**Repro steps:**
- just add `services.AddDeliveryClient("second", Configuration, "DeliveryOptions", CustomServiceProviderType.Autofac);` to the Startup class of the .NET boilerplate

# Too many "Extensions"
The FQN of  `Kentico.Kontent.Delivery.Extensions.DependencyInjection.Extensions.ServiceCollectionExtensions` is crazily long.
Can we perhaps rename projects and classes and flatten the folder structure to have something like:

`Kentico.Kontent.Delivery.DependencyInjection.ServiceCollectionExtensions`?

# CustomServiceProvider naming inconsistency
- please rename everything that starts with `CustomServiceProvider`* to `NamedServiceProvider` to match the interface `INamedServiceProvider`

**Comment by tomasjurasek** [comment]
Changes
* The root namespace is `Kentico.Kontent.Delivery.Extensions.DependencyInjection`. 
* `NamedServiceProvider`
*  Fix `ConfigurationSection` binding

**Comment by petrsvihlik** [comment]
remaining: tests for `Kentico.Kontent.Delivery.Extensions.DependencyInjection.ServiceCollectionExtensions`

**Comment by petrsvihlik** [comment]
We really need some tests @tomasjurasek  :)

> System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Kentico.Kontent.Delivery.Extensions.DependencyInjection.INamedServiceProvider Lifetime: Singleton ImplementationType: Kentico.Kontent.Delivery.Extensions.DependencyInjection.AutofacServiceProvider': Unable to resolve service for type 'Autofac.IComponentContext' while attempting to activate 'Kentico.Kontent.Delivery.Extensions.DependencyInjection.AutofacServiceProvider'.) (Error while validating the service descriptor 'ServiceType: Kentico.Kontent.Delivery.Abstractions.IDeliveryClientFactory Lifetime: Singleton ImplementationType: Kentico.Kontent.Delivery.Extensions.DependencyInjection.NamedDeliveryClientFactory': Unable to resolve service for type 'Autofac.IComponentContext' while attempting to activate 'Kentico.Kontent.Delivery.Extensions.DependencyInjection.AutofacServiceProvider'.) (Error while validating the service descriptor 'ServiceType: DancingGoat.Repositories.ICafesRepository Lifetime: Singleton ImplementationType: DancingGoat.Repositories.CafesRepository': Unable to resolve service for type 'Autofac.IComponentContext' while attempting to activate 'Kentico.Kontent.Delivery.Extensions.DependencyInjection.AutofacServiceProvider'.)
>  ---> System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Kentico.Kontent.Delivery.Extensions.DependencyInjection.INamedServiceProvider Lifetime: Singleton ImplementationType: Kentico.Kontent.Delivery.Extensions.DependencyInjection.AutofacServiceProvider': Unable to resolve service for type 'Autofac.IComponentContext' while attempting to activate 'Kentico.Kontent.Delivery.Extensions.DependencyInjection.AutofacServiceProvider'.
>  ---> System.InvalidOperationException: Unable to resolve service for type 'Autofac.IComponentContext' while attempting to activate 'Kentico.Kontent.Delivery.Extensions.DependencyInjection.AutofacServiceProvider'.
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
>    --- End of inner exception stack trace ---
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)
>    --- End of inner exception stack trace ---
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)
>    at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
>    at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
>    at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
>    at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
>    at Microsoft.Extensions.Hosting.HostBuilder.Build()
>    at DancingGoat.Program.Main(String[] args) in C:\Users\petrs\Documents\GitHub\kontent-sample-app-net\DancingGoat\Program.cs:line 25
>  ---> (Inner Exception #1) System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Kentico.Kontent.Delivery.Abstractions.IDeliveryClientFactory Lifetime: Singleton ImplementationType: Kentico.Kontent.Delivery.Extensions.DependencyInjection.NamedDeliveryClientFactory': Unable to resolve service for type 'Autofac.IComponentContext' while attempting to activate 'Kentico.Kontent.Delivery.Extensions.DependencyInjection.AutofacServiceProvider'.
>  ---> System.InvalidOperationException: Unable to resolve service for type 'Autofac.IComponentContext' while attempting to activate 'Kentico.Kontent.Delivery.Extensions.DependencyInjection.AutofacServiceProvider'.
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.<>c__DisplayClass7_0.<GetCallSite>b__0(Type type)
>    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
>    --- End of inner exception stack trace ---
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)<---
> 
>  ---> (Inner Exception #2) System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: DancingGoat.Repositories.ICafesRepository Lifetime: Singleton ImplementationType: DancingGoat.Repositories.CafesRepository': Unable to resolve service for type 'Autofac.IComponentContext' while attempting to activate 'Kentico.Kontent.Delivery.Extensions.DependencyInjection.AutofacServiceProvider'.
>  ---> System.InvalidOperationException: Unable to resolve service for type 'Autofac.IComponentContext' while attempting to activate 'Kentico.Kontent.Delivery.Extensions.DependencyInjection.AutofacServiceProvider'.
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.<>c__DisplayClass7_0.<GetCallSite>b__0(Type type)
>    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.<>c__DisplayClass7_0.<GetCallSite>b__0(Type type)
>    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
>    --- End of inner exception stack trace ---
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)<---

**Comment by tomasjurasek** [comment]
@petrsvihlik that's correct behavior. You want to use the AutoFac provider without register the AutoFac container into your app.

**Comment by petrsvihlik** [comment]
Indeed, I was testing your attention :)

here's the easiest way to do it: https://github.com/Kentico/kontent-sample-app-net/pull/121 (for documentation purposes)

**Comment by petrsvihlik** [comment]
docs updated
