### ISSUE TITLE
Kentico.Kontent.Delivery.Caching Version 15.0.0.0-rc1

### ISSUE THREAD

**Issue by johnhydemtm365** [Kentico/kontent-delivery-sdk-net#269]
### Brief bug description

When working with distributed cache, redis locally, the cache does not seem to get cleared when we fire the webhook to invalidate the cache.
It is working fine with memory cache.

Granted there is a slight delay as the CDN needs updating.

### Repro steps
Go to content item update a property and click publish
get the content item via postman from the delivery api so we know when it updated on the CDN
Fire post request to webhook to invalidate the cache item

Works fine for memory caching but not redis caching

### Expected behavior
Clears the cache when using distributed mode

What the correct behavior is?
as above

**Comment by petrsvihlik** [comment]
Hi @johnhydemtm365 
unfortunately, this is not how the `IDistributedCache` works. See the details here: https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Caching-responses#distributedcachemanager

You can also read my previous discussion with @xantari [here](https://github.com/Kentico/kontent-delivery-sdk-net/issues/234#issuecomment-701970783).

I'm sorry, but there's nothing we can do about it. :(
