### ISSUE TITLE
DeliveryClientBuilder (without DI) returning LinkedItems with objects set to null

### ISSUE THREAD

**Issue by twadevs** [Kentico/kontent-delivery-sdk-net#271]
### Brief bug description

We are trying to create some integration tests using NUnit, using the DeliveryClientBuilder to create the client. But for some reason, it always returns the LinkedItems as objects set to null. 

Using DI via our Web API (.Net 5) project, it all works fine and returns the LinkedItems set correctly to the strongly typed objects.

We tried using the DeliveryClientBuilder within the Web API project, but with the same results.

### Repro steps

1. Setup a DeliveryClient without DI, as per the documentation: 
```
    var _client = DeliveryClientBuilder
    .WithOptions(builder => builder
        .WithProjectId("<YOUR_PROJECT_ID>")
	.UseProductionApi()
	.Build())
    .Build();
```
    
2. Get a content item async with linked items: 
```
await client.GetItemAsync<yourtype>("yourcodename").
```
3. Notice that the LinkedItems returns as objects set to null.

![image](https://user-images.githubusercontent.com/67626158/111927477-c57a3400-8aeb-11eb-83d7-9cf730d0596b.png)

### Expected behaviour

LinkedItems should not be set to null.

![image](https://user-images.githubusercontent.com/67626158/111927469-bbf0cc00-8aeb-11eb-9c51-867d83f11e45.png)

### Test environment

 - .Net 5, Web SDK, NUnit

**Comment by petrsvihlik** [comment]
Hi @twadevs ,
you need to use `.WithTypeProvider(customTypeProvider)` or `services.AddSingleton<ITypeProvider, CustomTypeProvider>();` (if you're using dependency injection.

I recommend reading the following articles:
- [Registering the DeliveryClient to the IServiceCollection in ASP.NET Core
](https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Registering-the-DeliveryClient-to-the-IServiceCollection-in-ASP.NET-Core)
- [Strong Types Explained – Code Generator
](https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Strong-Types-Explained-%E2%80%93-Code-Generator)
- [Working with strongly typed models
](https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Working-with-strongly-typed-models)

I updated some of the samples there to always contain the registration of an `ITypeProvider`.

The type provider allows runtime resolution of CLR types <-> Content types in Kontent.

**Comment by twadevs** [comment]
Thanks, @petrsvihlik, that works.
