### ISSUE TITLE
Return empty objects with IDs where "depth" parameter prevents object return

### ISSUE THREAD

**Issue by rossb-mmt** [Kentico/kontent-delivery-sdk-net#279]
### Motivation

Returning a content item, which has a linked item element, with a depth of 1, will return a typed object which appears to have no items in that property, even though the underlying API call has returned the IDs (but not the content) of the linked items. There isn't currently a way to access those IDs to make the additional API calls to retrieve them.

### Proposed solution

We could return a "ghost" object which has no content except the ID for items which are linked but whose detailed content is missing from the API call return.

**Comment by MiroKentico** [comment]
Hello ross-mmt,

I will reproduce you scenario and analyze possible solutions (including the one you proposed). I will keep you informed.

Best Regards
  Miroslav

**Comment by Simply007** [comment]
More context in #281

**Comment by Simply007** [comment]
rename to `PropertyName`
