### ISSUE TITLE
Testing helper class DeliveryClientFactory is not race condition safe

### ISSUE THREAD

**Issue by MiroKentico** [Kentico/kontent-delivery-sdk-net#282]
### Issue description

There are some flaky tests, that caused failure of build & test actions. For example in run https://github.com/Kentico/kontent-delivery-sdk-net/runs/3688772162?check_suite_focus=true there was a test failure

`Passed Kentico.Kontent.Delivery.Tests.ContentLinkResolverTests.ContentLinkIsResolved [< 1 ms]
168
  Failed Kentico.Kontent.Delivery.Tests.QueryParameters.IncludeTotalCountTests.GetItemsTyped_DeliveryOptionsWithIncludeTotalCount_IncludeTotalCountParameterAdded [30 ms]
169
  Error Message:
170
   System.ArgumentException : Object 'Kentico.Kontent.Delivery.Tests.Models.ContentTypes.CustomTypeProvider' of type Kentico.Kontent.Delivery.Tests.Models.ContentTypes.CustomTypeProvider is not recognized as a fake object.
171
  Stack Trace:
172
     at FakeItEasy.Core.DefaultFakeManagerAccessor.GetFakeManager(Object proxy) in`

### What went wrong?

It seems, that current implementation of `DeliveryClientFactory` use static members in a way, that doesn't guarantee outcome if factory methods. The reason is, that usage of `GetMockedDeliveryClientWithProjectId` changes its internal state. It sets internal data to data from one test case execution. But another test case depend on default state data and therefore fails. If we are lucky, test cases are executed in an order, that doesn't lead into internal data change before its usage. But if we are not lucky, test run fails.

### Expected behavior

My first guess is, that `GetMockedDeliveryClientWithProjectId` must not propagate its parameters data into its internal state. These parameter data should only shape result product of this method within one single call. I would additionally suggest also some changes in signatures of static variables (rename, make it readonly ... to be clear that there are in fact mocks/fakes). 

To be on safe side, usage of this factory class should be analysed properly. Because changes of internal state might be intended, just implementation with some unwanted side effects.

**Comment by Simply007** [comment]
Fixed by https://github.com/Kentico/kontent-delivery-sdk-net/pull/283
