### ISSUE TITLE
Project folder - project file naming mismatch

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/kontent-delivery-sdk-net#304]
![image](https://user-images.githubusercontent.com/9810625/143572159-d2491412-d51b-4dfd-9689-bc02a836535d.png)

**Comment by Simply007** [comment]
This issue was fixed in #300. 

The folders are already unified in https://github.com/Kentico/kontent-delivery-sdk-net/tree/vNext

**Comment by petrsvihlik** [comment]
oh, I see.
any reason to call it `Kentico.Kontent.Delivery.Urls` and not just `Kentico.Kontent.Urls`
-> there was an idea to have a generic and very lightweight "Urls" package that would sit on top of `Kentico.Kontent.Abstractions` and packages like Kontent.Statiq would not have to be dependent on the whole `Kentico.Kontent.Delivery` package. this package would later on contain all URL handling related to Kentico Kontent (including MAPI) and [edit links](https://github.com/Kentico/kontent-management-sdk-net/tree/master/Kentico.Kontent.Management.Helpers.Tests).

**Comment by petrsvihlik** [comment]
not to mention the breaking change :)
![image](https://user-images.githubusercontent.com/9810625/143575022-a3b757f1-07b5-4a55-bb96-f04e21d9bb4d.png)

**Comment by Simply007** [comment]
> oh, I see. any reason to call it `Kentico.Kontent.Delivery.Urls` and not just `Kentico.Kontent.Urls`? -> there was an idea to have a generic and very lightweight "Urls" package that would sit on top of `Kentico.Kontent.Abstractions` and packages like Kontent.Statiq would not have to be dependent on the whole `Kentico.Kontent.Delivery` package. this package would later on contain all URL handling related to Kentico Kontent (including MAPI) and [edit links](https://github.com/Kentico/kontent-management-sdk-net/tree/master/Kentico.Kontent.Management.Helpers.Tests).

Yeap, but then there is a section https://github.com/Kentico/kontent-delivery-sdk-net/tree/vNext/Kentico.Kontent.Delivery.Urls/QueryParameters that is tied to Delivery API.

It might be possible to split the query parameters and `DeliveryEndpointUrlBuilder` into `Kentico.Kontent.Delivery.Urls` and keep the `ImageTransfromation` in `Kentico.Kontent.Urls` package. What do you think?

**Comment by petrsvihlik** [comment]
There are two ways to do it:

have 1 package with:
- Kentico.Kontent.Urls
  - Kentico.Kontent.Urls.Delivery
  - Kentico.Kontent.Urls.Management
  - Kentico.Kontent.Urls.ImageTransformation

or have 3 packages:

- Kentico.Kontent.Delivery.Urls
- Kentico.Kontent.Management.Urls
- Kentico.Kontent.ImageTransformation.Urls

**Comment by Simply007** [comment]
OK, I will keep this issue open and we will decide, how to deal with it. My current preference is:

Kentico.Kontent.Delivery.Urls
~Kentico.Kontent.Management.Urls~ -> this could be done as a part of #249
Kentico.Kontent.ImageTransformation.Urls

But let's keep the final decision for maintainers sync.

**Comment by Simply007** [comment]
We will decide about final namespaces on Thu 2021-12-09 (now I am more in favor of `Kentico.Kontent.Urls` 👼🏼).

**Comment by Simply007** [comment]
We have decided fot this approach:

Kentico.Kontent.Urls (one package with namesapces)
- Kentico.Kontent.Urls.Delivery
- Kentico.Kontent.Urls.Management
- Kentico.Kontent.Urls.ImageTransformation

**Comment by petrsvihlik** [comment]
lovely

**Comment by Simply007** [comment]
Fixed in #310 

I am going to release another beta an notify about it in #305
