### ISSUE TITLE
Add config option for default rendition preset to be applied

### ISSUE THREAD

**Issue by Suzii** [Kentico/kontent-delivery-sdk-net#318]
### Motivation

Users are having a hard time adopting the new asset renditions feature as the SDKs always return the original asset URL by default. We'd like to add an option to configure the default preset codename to be applied when such rendition exists in the Delivery API response.

Underlying Jira issue: https://kentico.atlassian.net/browse/KCL-8387

### Proposed solution

Let's get inspired by the JS implementation: https://github.com/Kentico/kontent-delivery-sdk-js/pull/336

**Comment by Suzii** [comment]
See the linked PR and please, take a close look at this change (I think it was a bug): https://github.com/Kentico/kontent-delivery-sdk-net/pull/320/files#diff-41f337b8d1d0e7995f0335ec5851944005dc3edd57b1a651cfea71b927e1fca9L223

**Comment by Suzii** [comment]
PR has been merged. Can we close this issue @MiroKentico?

**Comment by MiroKentico** [comment]
Yes, I am closing it.
