### ISSUE TITLE
SystemTypeEqualsFilter should inherit from EqualsFilter

### ISSUE THREAD

**Issue by frederikstonge** [Kentico/kontent-delivery-sdk-net#334]
Using this filter doesn't work as it doesn't specify the operator to use in Filter.

**Comment by MiroKentico** [comment]
Hi @frederikstonge, could you please provide some description of your use of `SystemTypeEqualsFilter `, what you expect to happen and what the actual result is ? You can also use some code samples, if feasible.

**Comment by frederikstonge** [comment]
I tought it was the issue but turns out it wasn't . My bad, you can close the issue.
