### ISSUE TITLE
Web hook for assets

### ISSUE THREAD

**Issue by markuspersso** [Kentico/kontent-delivery-sdk-net#339]
### Motivation

We have one web frontend inside China, one in japan, one in europe and one in USA. To be able to give our users the best performance possible we need to have the content as close to the users as possible. Some of the content, for example some images and pdf files, are used in the search engine that resides beside our frontend nodes. This content is not referenced by any pages in the CMS
So we want to distribute all the assets to our own CDN. Therefore we want to know when a specific asset is being changed so that we can update our own nodes in the CDN

### Proposed solution

Web hook similar to the ones for content items

### Additional context

Add any other context, screenshots, or reference links about the feature request here.

**Comment by MiroKentico** [comment]
Hello @markuspersso, thank you for the feature request. We will discuss this within developer teams and write you back.

Just for your info, due to planned vacations and some webhooks related improvements already in analysis/preparation, this might take a bit longer than usual.

**Comment by MiroKentico** [comment]
So we managed already to discuss this with @Simply007.

As this is in fact Kontent.ai product request, that would not result in change in Delivery SDK itself, I am closing this issue.

You can check https://feedback.kontent.ai/tabs/13-under-consideration (section Integration) to see what Kontent.ai product features are under consideration for Webhooks.

**Comment by MiroKentico** [comment]
@markuspersso just for your info, I have forwarded this to our Customer Success team.
