### ISSUE TITLE
Set up code coverage

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/kontent-delivery-sdk-net#69]
Generating coverage:
- `dotnet test --collect:"Code Coverage"` only works if Visual Studio Enterprise is installed.
  - appveyor has only the [community edition](https://www.appveyor.com/docs/windows-images-software/#visual-studio-2017)
- [coverlet](https://github.com/tonerdo/coverlet)
  - example: [`coverlet .\bin\Debug\netcoreapp2.1\hanselminutes.core.tests.dll --target "dotnet" --targetargs "test --no-build"`](https://www.hanselman.com/blog/NETCoreCodeCoverageAsAGlobalToolWithCoverlet.aspx)
  - or: `dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./lcov .\hanselminutes.core.tests` for nuget package

- [ ] Compare and pick a code coverage service
  - Comparisons:
    - https://stackshare.io/stackups/codecov-vs-coveralls
    - https://www.slant.co/topics/2188/versus/~codecov_vs_coveralls_vs_code-climate
  - Services:
    - [Code Climate](https://codeclimate.com/) - we slightly prefer this as we use it in [other repos](https://github.com/Kentico/delivery-sdk-php)
    - [Codecov](https://codecov.io/)
    - [Coveralls](https://coveralls.io/)
- [ ] Set it up

Examples for .NET Standard libraries:
- https://github.com/keenlabs/keen-sdk-net/blob/master/.appveyor.yml

**Comment by PetrSvirak** [comment]
You mention various static analysis services, have you considered SonarCloud? 

We have just set-up [SonarCloud](https://sonarcloud.io/component_measures?branch=develop&id=Kentico_kentico-cloud-docs-github-sync) with NUnit tests and Coverlet coverage [in kentico-cloud-docs-github-sync repository (using Travis)](https://github.com/Kentico/kentico-cloud-docs-github-sync/blob/7c61c67136121bb0b10b3d602d2af32e4ffacf90/.travis.yml) – its technology stack there is pretty similar to this SDK. Long story short, we have chosen SonarQube (hosted in SonarCloud) for we though its static analysis brings us most valueable advices while it is free for open-source projects. 

It should also be available for AppVeyor as one of my colleagues has set it up [in his project](https://github.com/pthutta/kentico-onboarding-cs/blob/master/appveyor.yml). Moreover, Travis does not have SonarQube plugin that would work with .net core (so we kind of had to [replicate its logic](https://github.com/Kentico/kentico-cloud-docs-github-sync/blob/7c61c67136121bb0b10b3d602d2af32e4ffacf90/.travis/sonar-configurator.sh)) while AppVeyor seems to have a bot that [comments to PRs](https://github.com/pthutta/kentico-onboarding-cs/pull/4#pullrequestreview-175824058) – at least for full framework, but I guess it will work .net core as well in AppVeyor's case.

**Comment by petrsvihlik** [comment]
I'm ok with whatever tool will work fine for us.

**Comment by petrsvihlik** [comment]
https://www.nuget.org/packages/coverlet.collector/
