### ISSUE TITLE
Let the SDK bypass the CDN for particular requests

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/kontent-delivery-sdk-net#76]
### Motivation

Currently, the [DeliveryClient](https://github.com/Kentico/delivery-sdk-net/blob/master/KenticoCloud.Delivery/DeliveryClient.cs) can either be configured to utilize or circumvent the CDN of Kentico Kontent, as a whole. One of the pitfalls of this is when an app [clears its cached Kentico Kontent data](https://github.com/Kentico/cloud-boilerplate-net/blob/master/src/content/CloudBoilerplateNet/Services/ReactiveCacheManager.cs#L225) and needs to fetch the most-up-to-date content in the very subsequent Delivery request.

### Design guidelines

Allow the SDK to sense whether it should use the `X-KC-Wait-For-Loading-New-Content` header for each _particular request_.

Based on the signal, the SDK should either use the header or not.

The logic that decides whether to send the signal, it should be outside the SDK (eg. in our [boilerplate project](https://github.com/Kentico/cloud-boilerplate-net)).

If no signal is sent explicitly, the SDK should **not** use the header (ie. not bypass the CDN).

**Comment by JanLenoch** [comment]
After a discussion with @petrsvihlik , we agreed on the following:

* It is desirable to have some means of signaling the need to use the `X-KC-Wait-For-Loading-New-Content` header for a _particular request_. Based on the signal, the SDK should either use the header or not.
* The logic that decides whether to send the signal, it should be outside the SDK (eg. in our boilerplate project).
* If no signal is sent explicitly, the SDK should **not** use the header (ie. not bypass the CDN).

**Comment by petrsvihlik** [comment]
nobody requested this functionality... allowing multiple differently configured instances of `IDeliveryClient` in a single app is apparently enough
